---
title: Spark SQL Job Data Analysis
author: Zhengyu Zhou
format: html
embed-resources: true
date: '2025-10-18'
date-format: long
execute:
  echo: true
jupyter: python3
---


```{python}
from pyspark.sql import SparkSession

# Start a Spark session
spark = SparkSession.builder.appName("JobPostingsAnalysis").getOrCreate()

# Load the CSV file into a Spark DataFrame
df = spark.read.option("header", "true").option("inferSchema", "true").option("multiLine", "true").option("escape", "\"").csv("data/job_postings.csv")

# 3. Register the DataFrame as a temporary SQL table
df.createOrReplaceTempView("jobs")
```

```{python}
# Verify the Data

# Display the first five rows
df.show(5)

# Show the schema (column names & data types)
df.printSchema()
```

```{python}
import pandas as pd

# read .xlsx and convert to .csv
excel_path = "data/job_postings.xlsx"   
csv_path   = "data/job_postings.csv"

# csv file
df = pd.read_excel(excel_path, engine="openpyxl")
df.to_csv(csv_path, index=False)

print("Converted", csv_path)
print("len:", len(df), "columns:", len(df.columns))
```

```{python}
#How many job postings we have in the dataset?
total_jobs = spark.sql("""
    SELECT COUNT(*) AS total_postings
    FROM jobs
""")
total_jobs.show()
```

We have 72,476 total postings.

```{python}
#Find the top 5 most common job titles
top_titles = spark.sql("""
    SELECT TITLE_NAME, COUNT(*) AS job_count
    FROM jobs
    WHERE TITLE_NAME IS NOT NULL
                       AND TITLE_NAME !='Unclassified'
    GROUP BY TITLE_NAME
    ORDER BY job_count DESC
    LIMIT 5
""")
top_titles.show(truncate=False)
```

Top 5 most common job titles
Data Analysts
Business Intelligence Analysts
Enterprise Architects 
Oracle Cloud HCM Consultants
Data Modelers

```{python}
#Find the average salary for each employment type
top_titles = spark.sql("""
    SELECT 
        EMPLOYMENT_TYPE_NAME,
        ROUND(AVG(SALARY),2) AS avg_salary,
        COUNT(*) AS job_count
    FROM jobs
    GROUP BY EMPLOYMENT_TYPE_NAME
    ORDER BY job_count DESC
""")
top_titles.show()
```

Full-time employment offers both the highest pay and the largest number of opportunities in this dataset — consistent with real-world job market patterns

```{python}
#What five states have the most job postings
top_titles = spark.sql("""
    SELECT STATE_NAME, COUNT(*) AS job_count
    FROM jobs
    GROUP BY STATE_NAME
    ORDER BY job_count DESC
    LIMIT 5
""")
top_titles.show(truncate=False)
```

Employment opportunities are concentrated in large and economically diverse states like Texas and California.

```{python}
#Calculate the salary range (max-min) for each job title in a California
salary_range_ca = spark.sql("""
    SELECT 
        TITLE_NAME,
        MAX(SALARY) AS max_salary,
        MIN(SALARY) AS min_salary,
        ROUND(MAX(SALARY) - MIN(SALARY),2) AS salary_range,
        COUNT(*) AS job_count
    FROM jobs
    WHERE 
        STATE_NAME = 'California'
        AND TITLE_NAME IS NOT NULL
        AND TITLE_NAME !='Unclassified'
        AND SALARY IS NOT NULL
    GROUP BY TITLE_NAME
    ORDER BY salary_range DESC
    LIMIT 5
""")
salary_range_ca.show(truncate=False)
```

In California, the salary gap for senior technical architecture positions is the largest. This not only reflects the complexity of these positions, but also indicates that there are significant differences in compensation based on years of experience and the size of the company.

```{python}
#What top 5 industries have the highest average salaries, and ,more than 100 job postings?
top_industries = spark.sql("""
    SELECT 
        LIGHTCAST_SECTORS_NAME AS industry,
        ROUND(AVG(SALARY), 2) AS avg_salary,
        COUNT(*) AS job_count
    FROM jobs
    WHERE LIGHTCAST_SECTORS_NAME IS NOT NULL
      AND SALARY IS NOT NULL
    GROUP BY LIGHTCAST_SECTORS_NAME
    HAVING COUNT(*) > 100
    ORDER BY avg_salary DESC
    LIMIT 5
""")

top_industries.show(truncate=False)
```

Professionals with skills in cybersecurity, artificial intelligence, and data privacy are the most highly sought-after in the job market, and their salaries typically exceed $130,000.

